/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    pages: Page;
    posts: Post;
    media: Media;
    categories: Category;
    products: Product;
    reservations: Reservation;
    users: User;
    redirects: Redirect;
    forms: Form;
    'form-submissions': FormSubmission;
    search: Search;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-folders': FolderInterface;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    'payload-folders': {
      documentsAndFolders: 'payload-folders' | 'media';
    };
  };
  collectionsSelect: {
    pages: PagesSelect<false> | PagesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    reservations: ReservationsSelect<false> | ReservationsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    forms: FormsSelect<false> | FormsSelect<true>;
    'form-submissions': FormSubmissionsSelect<false> | FormSubmissionsSelect<true>;
    search: SearchSelect<false> | SearchSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-folders': PayloadFoldersSelect<false> | PayloadFoldersSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    header: Header;
    footer: Footer;
  };
  globalsSelect: {
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: {
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  hero: {
    type: 'none' | 'highImpact' | 'mediumImpact' | 'lowImpact' | 'microVisuals' | 'heroSoria';
    richText?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    links?:
      | {
          link: {
            type?: ('reference' | 'custom') | null;
            newTab?: boolean | null;
            reference?:
              | ({
                  relationTo: 'pages';
                  value: number | Page;
                } | null)
              | ({
                  relationTo: 'posts';
                  value: number | Post;
                } | null);
            url?: string | null;
            label: string;
            /**
             * Choose how the link should be rendered.
             */
            appearance?: ('default' | 'outline') | null;
          };
          id?: string | null;
        }[]
      | null;
    media?: (number | null) | Media;
    microVisuals?: {
      title?: string | null;
      /**
       * External MP4 URL (e.g. CDN). If set, this overrides the uploaded file below.
       */
      videoUrl?: string | null;
      /**
       * MP4 recommended. Used when Video URL is empty.
       */
      backgroundVideo?: (number | null) | Media;
      navItems?:
        | {
            link: {
              type?: ('reference' | 'custom') | null;
              newTab?: boolean | null;
              reference?:
                | ({
                    relationTo: 'pages';
                    value: number | Page;
                  } | null)
                | ({
                    relationTo: 'posts';
                    value: number | Post;
                  } | null);
              url?: string | null;
              label: string;
            };
            id?: string | null;
          }[]
        | null;
      leftCaption?: string | null;
      rightCaption?: string | null;
      signIn: {
        type?: ('reference' | 'custom') | null;
        newTab?: boolean | null;
        reference?:
          | ({
              relationTo: 'pages';
              value: number | Page;
            } | null)
          | ({
              relationTo: 'posts';
              value: number | Post;
            } | null);
        url?: string | null;
        label: string;
      };
      tryItFree: {
        type?: ('reference' | 'custom') | null;
        newTab?: boolean | null;
        reference?:
          | ({
              relationTo: 'pages';
              value: number | Page;
            } | null)
          | ({
              relationTo: 'posts';
              value: number | Post;
            } | null);
        url?: string | null;
        label: string;
      };
      primaryCta: {
        type?: ('reference' | 'custom') | null;
        newTab?: boolean | null;
        reference?:
          | ({
              relationTo: 'pages';
              value: number | Page;
            } | null)
          | ({
              relationTo: 'posts';
              value: number | Post;
            } | null);
        url?: string | null;
        label: string;
      };
      secondaryCta: {
        type?: ('reference' | 'custom') | null;
        newTab?: boolean | null;
        reference?:
          | ({
              relationTo: 'pages';
              value: number | Page;
            } | null)
          | ({
              relationTo: 'posts';
              value: number | Post;
            } | null);
        url?: string | null;
        label: string;
      };
      showSecondaryIcon?: boolean | null;
    };
    heroSoria?: {
      /**
       * Opcional. Línea breve sobre el título principal.
       */
      eyebrow?: {
        root: {
          type: string;
          children: {
            type: any;
            version: number;
            [k: string]: unknown;
          }[];
          direction: ('ltr' | 'rtl') | null;
          format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
          indent: number;
          version: number;
        };
        [k: string]: unknown;
      } | null;
      /**
       * Encabezado principal. Por defecto se renderiza con el mismo estilo display que MicroVisuals.
       */
      title?: {
        root: {
          type: string;
          children: {
            type: any;
            version: number;
            [k: string]: unknown;
          }[];
          direction: ('ltr' | 'rtl') | null;
          format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
          indent: number;
          version: number;
        };
        [k: string]: unknown;
      } | null;
      /**
       * Texto descriptivo bajo el título.
       */
      subtitle?: {
        root: {
          type: string;
          children: {
            type: any;
            version: number;
            [k: string]: unknown;
          }[];
          direction: ('ltr' | 'rtl') | null;
          format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
          indent: number;
          version: number;
        };
        [k: string]: unknown;
      } | null;
      /**
       * Hasta dos botones bajo el subtítulo. Cada botón es un link normal de Payload (puede apuntar a una página interna o a una URL externa).
       */
      buttons?:
        | {
            link: {
              type?: ('reference' | 'custom') | null;
              newTab?: boolean | null;
              reference?:
                | ({
                    relationTo: 'pages';
                    value: number | Page;
                  } | null)
                | ({
                    relationTo: 'posts';
                    value: number | Post;
                  } | null);
              url?: string | null;
              label: string;
            };
            appearance?: ('primary' | 'secondary') | null;
            /**
             * Por defecto, la tipografía del cuerpo de texto del hero.
             */
            fontFamily?:
              | (
                  | 'default'
                  | '"Instrument Serif", serif'
                  | 'Arial, sans-serif'
                  | '"Times New Roman", serif'
                  | 'Georgia, serif'
                  | 'Verdana, sans-serif'
                  | 'Helvetica, Arial, sans-serif'
                  | '"Courier New", monospace'
                  | '"Roboto", sans-serif'
                  | '"Open Sans", sans-serif'
                  | '"Lato", sans-serif'
                  | '"Montserrat", sans-serif'
                  | '"Playfair Display", serif'
                  | '"Inter", sans-serif'
                  | '"Poppins", sans-serif'
                  | '"Raleway", sans-serif'
                )
              | null;
            /**
             * Opcional. Ej.: #111111 o oklch(0.2 0 0).
             */
            backgroundColor?: string | null;
            textColor?: string | null;
            id?: string | null;
          }[]
        | null;
      /**
       * Cada elemento es una "polaroid" mostrada en la fila bajo los botones. El orden importa: las tarjetas se inclinan automáticamente alternando ±, salvo que sobrescribas el ángulo.
       */
      gallery?:
        | {
            image: number | Media;
            /**
             * Opcional. Si lo dejas vacío, las tarjetas se inclinan alternando ±5° en función del orden.
             */
            rotation?: number | null;
            alt?: string | null;
            id?: string | null;
          }[]
        | null;
      /**
       * Opcional. Cualquier color CSS (#hex, rgb, oklch…).
       */
      titleColor?: string | null;
      /**
       * Por defecto usa el estilo display del hero MicroVisuals.
       */
      titleFontFamily?:
        | (
            | 'default'
            | '"Instrument Serif", serif'
            | 'Arial, sans-serif'
            | '"Times New Roman", serif'
            | 'Georgia, serif'
            | 'Verdana, sans-serif'
            | 'Helvetica, Arial, sans-serif'
            | '"Courier New", monospace'
            | '"Roboto", sans-serif'
            | '"Open Sans", sans-serif'
            | '"Lato", sans-serif'
            | '"Montserrat", sans-serif'
            | '"Playfair Display", serif'
            | '"Inter", sans-serif'
            | '"Poppins", sans-serif'
            | '"Raleway", sans-serif'
          )
        | null;
      subtitleColor?: string | null;
      /**
       * Por defecto usa el cuerpo de texto MicroVisuals (Barlow).
       */
      subtitleFontFamily?:
        | (
            | 'default'
            | '"Instrument Serif", serif'
            | 'Arial, sans-serif'
            | '"Times New Roman", serif'
            | 'Georgia, serif'
            | 'Verdana, sans-serif'
            | 'Helvetica, Arial, sans-serif'
            | '"Courier New", monospace'
            | '"Roboto", sans-serif'
            | '"Open Sans", sans-serif'
            | '"Lato", sans-serif'
            | '"Montserrat", sans-serif'
            | '"Playfair Display", serif'
            | '"Inter", sans-serif'
            | '"Poppins", sans-serif'
            | '"Raleway", sans-serif'
          )
        | null;
      eyebrowColor?: string | null;
      /**
       * Por defecto usa la misma tipografía que el hero MicroVisuals (Instrument Serif + Barlow).
       */
      eyebrowFontFamily?:
        | (
            | 'default'
            | '"Instrument Serif", serif'
            | 'Arial, sans-serif'
            | '"Times New Roman", serif'
            | 'Georgia, serif'
            | 'Verdana, sans-serif'
            | 'Helvetica, Arial, sans-serif'
            | '"Courier New", monospace'
            | '"Roboto", sans-serif'
            | '"Open Sans", sans-serif'
            | '"Lato", sans-serif'
            | '"Montserrat", sans-serif'
            | '"Playfair Display", serif'
            | '"Inter", sans-serif'
            | '"Poppins", sans-serif'
            | '"Raleway", sans-serif'
          )
        | null;
      /**
       * Opcional. Por defecto, un degradado suave crema → blanco como en la referencia.
       */
      backgroundColor?: string | null;
    };
  };
  layout: (
    | CallToActionBlock
    | ContentBlock
    | MediaBlock
    | ArchiveBlock
    | FormBlock
    | ProductsBlock
    | LayoutSoriaBlock
    | LayoutSoria2Block
    | LocationBlock
    | ServiciosSoriaBlock
    | FAQsBlock
  )[];
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
  };
  publishedAt?: string | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  heroImage?: (number | null) | Media;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  relatedPosts?: (number | Post)[] | null;
  categories?: (number | Category)[] | null;
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
  };
  publishedAt?: string | null;
  authors?: (number | User)[] | null;
  populatedAuthors?:
    | {
        id?: string | null;
        name?: string | null;
      }[]
    | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  caption?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  folder?: (number | null) | FolderInterface;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    square?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    small?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    medium?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    xlarge?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-folders".
 */
export interface FolderInterface {
  id: number;
  name: string;
  folder?: (number | null) | FolderInterface;
  documentsAndFolders?: {
    docs?: (
      | {
          relationTo?: 'payload-folders';
          value: number | FolderInterface;
        }
      | {
          relationTo?: 'media';
          value: number | Media;
        }
    )[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  folderType?: 'media'[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  title: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  parent?: (number | null) | Category;
  breadcrumbs?:
    | {
        doc?: (number | null) | Category;
        url?: string | null;
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionBlock".
 */
export interface CallToActionBlock {
  background: {
    type: 'none' | 'image' | 'video' | 'solid' | 'gradient';
    image?: (number | null) | Media;
    /**
     * HTTPS URL to YouTube (or other allowed secure providers).
     */
    videoURL?: string | null;
    /**
     * CSS color value (e.g. #0f172a, rgb(...), hsl(...))
     */
    solidColor?: string | null;
    gradientFrom?: string | null;
    gradientTo?: string | null;
    /**
     * Optional dark overlay to improve text contrast (0–1). Applies to image/video backgrounds.
     */
    overlayOpacity?: number | null;
  };
  /**
   * Where the CTA buttons appear on desktop layouts.
   */
  buttonsPosition?: ('right' | 'left' | 'bottom') | null;
  richText?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  links?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null);
          url?: string | null;
          label: string;
          /**
           * Choose how the link should be rendered.
           */
          appearance?: ('default' | 'outline') | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'cta';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock".
 */
export interface ContentBlock {
  columns?:
    | {
        size?: ('oneThird' | 'half' | 'twoThirds' | 'full') | null;
        richText?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        enableLink?: boolean | null;
        link?: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null);
          url?: string | null;
          label: string;
          /**
           * Choose how the link should be rendered.
           */
          appearance?: ('default' | 'outline') | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'content';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock".
 */
export interface MediaBlock {
  media: number | Media;
  id?: string | null;
  blockName?: string | null;
  blockType: 'mediaBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ArchiveBlock".
 */
export interface ArchiveBlock {
  introContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  populateBy?: ('collection' | 'selection') | null;
  relationTo?: 'posts' | null;
  categories?: (number | Category)[] | null;
  limit?: number | null;
  selectedDocs?:
    | {
        relationTo: 'posts';
        value: number | Post;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'archive';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormBlock".
 */
export interface FormBlock {
  form: number | Form;
  enableIntro?: boolean | null;
  introContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'formBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms".
 */
export interface Form {
  id: number;
  title: string;
  fields?:
    | (
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            defaultValue?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'checkbox';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'country';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'email';
          }
        | {
            message?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'message';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'number';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            placeholder?: string | null;
            options?:
              | {
                  label: string;
                  value: string;
                  id?: string | null;
                }[]
              | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'select';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'state';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'text';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'textarea';
          }
      )[]
    | null;
  submitButtonLabel?: string | null;
  /**
   * Choose whether to display an on-page message or redirect to a different page after they submit the form.
   */
  confirmationType?: ('message' | 'redirect') | null;
  confirmationMessage?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  redirect?: {
    url: string;
  };
  /**
   * Send custom emails when the form submits. Use comma separated lists to send the same email to multiple recipients. To reference a value from this form, wrap that field's name with double curly brackets, i.e. {{firstName}}. You can use a wildcard {{*}} to output all data and {{*:table}} to format it as an HTML table in the email.
   */
  emails?:
    | {
        emailTo?: string | null;
        cc?: string | null;
        bcc?: string | null;
        replyTo?: string | null;
        emailFrom?: string | null;
        subject: string;
        /**
         * Enter the message that should be sent in this email.
         */
        message?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ProductsBlock".
 */
export interface ProductsBlock {
  title?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  populateBy?: ('collection' | 'selection') | null;
  limit?: number | null;
  selectedProducts?: (number | Product)[] | null;
  /**
   * Si está activado, los productos se muestran en un carrusel horizontal en lugar de la cuadrícula apilada.
   */
  carousel?: boolean | null;
  /**
   * Opcional. Cualquier color CSS válido (#hex, rgb, oklch...). Ej.: #f6f3ec
   */
  backgroundColor?: string | null;
  /**
   * Opcional. Color base del título, descripción y tarjetas. Ej.: #1a1a1a
   */
  textColor?: string | null;
  /**
   * Por defecto usa la tipografía editorial del bloque.
   */
  titleFontFamily?:
    | (
        | 'default'
        | '"Instrument Serif", serif'
        | 'Arial, sans-serif'
        | '"Times New Roman", serif'
        | 'Georgia, serif'
        | 'Verdana, sans-serif'
        | 'Helvetica, Arial, sans-serif'
        | '"Courier New", monospace'
        | '"Roboto", sans-serif'
        | '"Open Sans", sans-serif'
        | '"Lato", sans-serif'
        | '"Montserrat", sans-serif'
        | '"Playfair Display", serif'
        | '"Inter", sans-serif'
        | '"Poppins", sans-serif'
        | '"Raleway", sans-serif'
      )
    | null;
  /**
   * Tipografía aplicada al texto descriptivo y a las tarjetas de producto.
   */
  descriptionFontFamily?:
    | (
        | 'default'
        | '"Instrument Serif", serif'
        | 'Arial, sans-serif'
        | '"Times New Roman", serif'
        | 'Georgia, serif'
        | 'Verdana, sans-serif'
        | 'Helvetica, Arial, sans-serif'
        | '"Courier New", monospace'
        | '"Roboto", sans-serif'
        | '"Open Sans", sans-serif'
        | '"Lato", sans-serif'
        | '"Montserrat", sans-serif'
        | '"Playfair Display", serif'
        | '"Inter", sans-serif'
        | '"Poppins", sans-serif'
        | '"Raleway", sans-serif'
      )
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'productsBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  title: string;
  sku?: string | null;
  price: number;
  availability: 'in_stock' | 'limited' | 'out_of_stock';
  shortDescription: string;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  images?: (number | Media)[] | null;
  allowReservation?: boolean | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LayoutSoriaBlock".
 */
export interface LayoutSoriaBlock {
  /**
   * ID para enlaces ancla (ej: mi-seccion). Usar el mismo valor en el navbar en "Id ancla (misma página)".
   */
  anchorId?: string | null;
  richText?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  image?: {
    useMedia?: boolean | null;
    /**
     * Seleccione una imagen de la libreria
     */
    mediaImage?: (number | null) | Media;
    /**
     * Fija ancho y alto en vw/vh. En escritorio (pantallas lg o más) use los valores de “escritorio”; en móvil puede usar valores distintos abajo o dejarlos vacíos para reutilizar los de escritorio.
     */
    useViewportSize?: boolean | null;
    /**
     * Pantallas ≥1024px (lg). Ej.: 80 → 80vw.
     */
    mediaWidthVw?: number | null;
    /**
     * Pantallas ≥1024px (lg). Ej.: 50 → 50vh.
     */
    mediaHeightVh?: number | null;
    /**
     * Pantallas menores a 1024px (móvil/tablet). Opcional: si rellena ancho y alto móvil, sustituyen a escritorio en pantallas pequeñas. Si vacío, se usan los de escritorio.
     */
    mediaWidthVwMobile?: number | null;
    /**
     * Pantallas menores a 1024px. Debe ir junto a “Ancho móvil” para aplicarse.
     */
    mediaHeightVhMobile?: number | null;
    /**
     * URL de la imagen cuando no se usa media subida
     */
    src?: string | null;
    alt?: string | null;
  };
  subHeadings?:
    | {
        icon?: {
          useMedia?: boolean | null;
          /**
           * Seleccione una imagen para el icono
           */
          mediaImage?: (number | null) | Media;
          /**
           * Codigo SVG del icono del subheading
           */
          iconSVG?: string | null;
          alt?: string | null;
        };
        content?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  buttons?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null);
          url?: string | null;
          label: string;
        };
        appearance?: ('default' | 'secondary' | 'outline' | 'link') | null;
        size?: ('sm' | 'lg' | 'clear') | null;
        iconSVG?: string | null;
        id?: string | null;
      }[]
    | null;
  invertLayout?: boolean | null;
  backgroundColor?: string | null;
  /**
   * Si está activo, el contenido (texto, subheadings, imagen y botones) usa el ancho en % del viewport; el color de fondo sigue a ancho completo. Si no lo marcas, el diseño no cambia.
   */
  applyCustomWidth?: boolean | null;
  /**
   * 0–100. Ej.: 50 = el contenido ocupa el 50% del ancho de la ventana, centrado; sin paddings laterales extra sobre ese ancho.
   */
  customWidthPercent?: number | null;
  /**
   * Opcional. Si lo dejas vacío, en móvil se usa el mismo “Ancho respecto a la pantalla (%)” que arriba. Si indicas un valor (0–100), solo en pantallas menores a 768px de ancho el bloque usará ese ancho; desde tablet y desktop sigue el campo principal.
   */
  customWidthPercentMobile?: number | null;
  textColor?: string | null;
  boldTextColor?: string | null;
  buttonBackgroundColor?: string | null;
  buttonTextColor?: string | null;
  fontFamily?:
    | (
        | 'default'
        | 'Arial, sans-serif'
        | '"Times New Roman", serif'
        | 'Georgia, serif'
        | 'Verdana, sans-serif'
        | 'Helvetica, Arial, sans-serif'
        | '"Courier New", monospace'
        | '"Roboto", sans-serif'
        | '"Open Sans", sans-serif'
        | '"Lato", sans-serif'
        | '"Montserrat", sans-serif'
        | '"Playfair Display", serif'
        | '"Inter", sans-serif'
        | '"Poppins", sans-serif'
        | '"Raleway", sans-serif'
      )
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'layoutSoria';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LayoutSoria2Block".
 */
export interface LayoutSoria2Block {
  /**
   * Opcional. ID para enlaces ancla (ej: compromiso). Solo letras, números, guiones y guión bajo.
   */
  anchorId?: string | null;
  heading: string;
  /**
   * Texto bajo el título (párrafo introductorio).
   */
  description?: string | null;
  /**
   * Tarjetas blancas con número destacado y etiqueta (p. ej. 1000+ / Clientes satisfechos).
   */
  stats?:
    | {
        /**
         * Ej.: 1000+, 25+
         */
        value: string;
        /**
         * Ej.: Clientes satisfechos
         */
        label: string;
        id?: string | null;
      }[]
    | null;
  image: number | Media;
  /**
   * Si lo dejas vacío, se usa el alt de la imagen en la librería.
   */
  imageAlt?: string | null;
  imagePosition?: ('right' | 'left') | null;
  backgroundColor?: string | null;
  headingColor?: string | null;
  descriptionColor?: string | null;
  statCardBackground?: string | null;
  statNumberColor?: string | null;
  statLabelColor?: string | null;
  /**
   * Tarjetas e imagen (mismo radio).
   */
  cornerRadius?: number | null;
  /**
   * Por defecto usa la misma tipografía que el hero MicroVisuals (Instrument Serif + Barlow).
   */
  fontFamily?:
    | (
        | 'default'
        | '"Instrument Serif", serif'
        | 'Arial, sans-serif'
        | '"Times New Roman", serif'
        | 'Georgia, serif'
        | 'Verdana, sans-serif'
        | 'Helvetica, Arial, sans-serif'
        | '"Courier New", monospace'
        | '"Roboto", sans-serif'
        | '"Open Sans", sans-serif'
        | '"Lato", sans-serif'
        | '"Montserrat", sans-serif'
        | '"Playfair Display", serif'
        | '"Inter", sans-serif'
        | '"Poppins", sans-serif'
        | '"Raleway", sans-serif'
      )
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'layoutSoria2';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LocationBlock".
 */
export interface LocationBlock {
  /**
   * Shown as the heading above the address and used as the business name in structured data.
   */
  businessName: string;
  /**
   * Short tagline shown under the heading (optional).
   */
  description?: string | null;
  address: {
    streetAddress: string;
    postalCode: string;
    addressLocality: string;
    addressRegion?: string | null;
    /**
     * Two-letter country code, e.g. ES for Spain.
     */
    addressCountry: string;
  };
  /**
   * In international format, e.g. +34 912 345 678
   */
  phone: string;
  email?: string | null;
  /**
   * On Google Maps: open your business → Share → "Embed a map" → copy the URL from the src="..." attribute. Must start with https://www.google.com/maps/embed.
   */
  embedUrl: string;
  /**
   * Find your business in Google Maps, right-click the pin, click the coordinates to copy them, and paste here.
   */
  geo?: {
    latitude?: number | null;
    longitude?: number | null;
  };
  /**
   * Add one entry per continuous time range. For split schedules (e.g. mornings + afternoons) add two entries with the same days.
   */
  openingHours?:
    | {
        daysOfWeek: ('Monday' | 'Tuesday' | 'Wednesday' | 'Thursday' | 'Friday' | 'Saturday' | 'Sunday')[];
        opens?: string | null;
        closes?: string | null;
        /**
         * Tick if these days are closed all day.
         */
        closed?: boolean | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Hint shown to Google for local listings. Not displayed on the page.
   */
  priceRange?: ('€' | '€€' | '€€€') | null;
  /**
   * Opcional. Cualquier color CSS válido (#hex, rgb, oklch...). Ej.: #f6f3ec
   */
  backgroundColor?: string | null;
  /**
   * Opcional. Color base aplicado al título y al texto de la dirección. Ej.: #1a1a1a
   */
  textColor?: string | null;
  /**
   * Aplica al nombre del negocio.
   */
  headingFontFamily?:
    | (
        | 'default'
        | '"Instrument Serif", serif'
        | 'Arial, sans-serif'
        | '"Times New Roman", serif'
        | 'Georgia, serif'
        | 'Verdana, sans-serif'
        | 'Helvetica, Arial, sans-serif'
        | '"Courier New", monospace'
        | '"Roboto", sans-serif'
        | '"Open Sans", sans-serif'
        | '"Lato", sans-serif'
        | '"Montserrat", sans-serif'
        | '"Playfair Display", serif'
        | '"Inter", sans-serif'
        | '"Poppins", sans-serif'
        | '"Raleway", sans-serif'
      )
    | null;
  /**
   * Aplica a la descripción, dirección, teléfono y horarios.
   */
  bodyFontFamily?:
    | (
        | 'default'
        | '"Instrument Serif", serif'
        | 'Arial, sans-serif'
        | '"Times New Roman", serif'
        | 'Georgia, serif'
        | 'Verdana, sans-serif'
        | 'Helvetica, Arial, sans-serif'
        | '"Courier New", monospace'
        | '"Roboto", sans-serif'
        | '"Open Sans", sans-serif'
        | '"Lato", sans-serif'
        | '"Montserrat", sans-serif'
        | '"Playfair Display", serif'
        | '"Inter", sans-serif'
        | '"Poppins", sans-serif'
        | '"Raleway", sans-serif'
      )
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'locationBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ServiciosSoriaBlock".
 */
export interface ServiciosSoriaBlock {
  /**
   * ID opcional para enlaces ancla (ej: servicios).
   */
  anchorId?: string | null;
  /**
   * Opcional. Línea breve encima del título.
   */
  eyebrow?: string | null;
  /**
   * Encabezado principal del bloque. Por defecto se renderiza con el mismo estilo que el headline del hero MicroVisuals.
   */
  title?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Párrafo descriptivo bajo el título.
   */
  subtitle?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Cada elemento es una tarjeta del carrusel. La primera tarjeta arranca expandida; las demás aparecen como tarjetas pequeñas a su lado y se expanden al hacer click o cuando el autoplay las selecciona.
   */
  services?:
    | {
        /**
         * Imagen que ocupa toda la tarjeta. Idealmente 1200×1500 o vertical.
         */
        image: number | Media;
        /**
         * Texto corto que aparece siempre en la esquina inferior de la tarjeta (badge tipo "Compra en tienda").
         */
        label?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        /**
         * Texto descriptivo que aparece bajo la etiqueta cuando la tarjeta está expandida.
         */
        description?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        /**
         * Opcional. Aparece arriba a la derecha cuando la tarjeta está expandida. Si no hay label, no se muestra el botón.
         */
        cta: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null);
          url?: string | null;
          label: string;
        };
        id?: string | null;
      }[]
    | null;
  autoplay?: boolean | null;
  /**
   * Solo aplica si "Avance automático" está activo.
   */
  autoplayMs?: number | null;
  /**
   * Opcional. Cualquier color CSS (#hex, rgb, oklch, etc.).
   */
  backgroundColor?: string | null;
  /**
   * Opcional. Por defecto hereda el color del bloque.
   */
  titleColor?: string | null;
  /**
   * Por defecto usa el estilo display del hero MicroVisuals.
   */
  titleFontFamily?:
    | (
        | 'default'
        | '"Instrument Serif", serif'
        | 'Arial, sans-serif'
        | '"Times New Roman", serif'
        | 'Georgia, serif'
        | 'Verdana, sans-serif'
        | 'Helvetica, Arial, sans-serif'
        | '"Courier New", monospace'
        | '"Roboto", sans-serif'
        | '"Open Sans", sans-serif'
        | '"Lato", sans-serif'
        | '"Montserrat", sans-serif'
        | '"Playfair Display", serif'
        | '"Inter", sans-serif'
        | '"Poppins", sans-serif'
        | '"Raleway", sans-serif'
      )
    | null;
  /**
   * Opcional.
   */
  subtitleColor?: string | null;
  /**
   * Por defecto usa el cuerpo de texto MicroVisuals (Barlow).
   */
  subtitleFontFamily?:
    | (
        | 'default'
        | '"Instrument Serif", serif'
        | 'Arial, sans-serif'
        | '"Times New Roman", serif'
        | 'Georgia, serif'
        | 'Verdana, sans-serif'
        | 'Helvetica, Arial, sans-serif'
        | '"Courier New", monospace'
        | '"Roboto", sans-serif'
        | '"Open Sans", sans-serif'
        | '"Lato", sans-serif'
        | '"Montserrat", sans-serif'
        | '"Playfair Display", serif'
        | '"Inter", sans-serif'
        | '"Poppins", sans-serif'
        | '"Raleway", sans-serif'
      )
    | null;
  /**
   * Aplica al label y a la descripción dentro de cada tarjeta.
   */
  cardTextColor?: string | null;
  /**
   * Aplica al label y a la descripción dentro de cada tarjeta.
   */
  cardFontFamily?:
    | (
        | 'default'
        | '"Instrument Serif", serif'
        | 'Arial, sans-serif'
        | '"Times New Roman", serif'
        | 'Georgia, serif'
        | 'Verdana, sans-serif'
        | 'Helvetica, Arial, sans-serif'
        | '"Courier New", monospace'
        | '"Roboto", sans-serif'
        | '"Open Sans", sans-serif'
        | '"Lato", sans-serif'
        | '"Montserrat", sans-serif'
        | '"Playfair Display", serif'
        | '"Inter", sans-serif'
        | '"Poppins", sans-serif'
        | '"Raleway", sans-serif'
      )
    | null;
  /**
   * Opcional. Por defecto blanco semitransparente.
   */
  ctaBackgroundColor?: string | null;
  /**
   * Opcional. Por defecto usa el color de primer plano.
   */
  ctaTextColor?: string | null;
  /**
   * Tipografía del botón superior cuando la tarjeta está activa.
   */
  ctaFontFamily?:
    | (
        | 'default'
        | '"Instrument Serif", serif'
        | 'Arial, sans-serif'
        | '"Times New Roman", serif'
        | 'Georgia, serif'
        | 'Verdana, sans-serif'
        | 'Helvetica, Arial, sans-serif'
        | '"Courier New", monospace'
        | '"Roboto", sans-serif'
        | '"Open Sans", sans-serif'
        | '"Lato", sans-serif'
        | '"Montserrat", sans-serif'
        | '"Playfair Display", serif'
        | '"Inter", sans-serif'
        | '"Poppins", sans-serif'
        | '"Raleway", sans-serif'
      )
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'serviciosSoria';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FAQsBlock".
 */
export interface FAQsBlock {
  /**
   * ID opcional para enlaces ancla (ej: preguntas-frecuentes).
   */
  anchorId?: string | null;
  /**
   * Encabezado principal del bloque (ej: "Preguntas frecuentes").
   */
  title?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Texto breve bajo el título.
   */
  subtitle?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Cada elemento es una pregunta con su respuesta desplegable.
   */
  items?:
    | {
        question: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        answer: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        /**
         * Si está marcada, la pregunta se mostrará abierta al cargar la página.
         */
        defaultOpen?: boolean | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Si está desactivado, al abrir una pregunta se cerrarán las demás (modo acordeón).
   */
  allowMultipleOpen?: boolean | null;
  /**
   * Cualquier color CSS (#hex, rgb, oklch...). Por defecto: negro.
   */
  backgroundColor?: string | null;
  /**
   * Por defecto: 64rem. Ej: 48rem, 800px, 100%.
   */
  maxWidth?: string | null;
  /**
   * Por defecto: blanco.
   */
  titleColor?: string | null;
  /**
   * Por defecto usa la misma tipografía que el hero MicroVisuals (Instrument Serif + Barlow).
   */
  titleFontFamily?:
    | (
        | 'default'
        | '"Instrument Serif", serif'
        | 'Arial, sans-serif'
        | '"Times New Roman", serif'
        | 'Georgia, serif'
        | 'Verdana, sans-serif'
        | 'Helvetica, Arial, sans-serif'
        | '"Courier New", monospace'
        | '"Roboto", sans-serif'
        | '"Open Sans", sans-serif'
        | '"Lato", sans-serif'
        | '"Montserrat", sans-serif'
        | '"Playfair Display", serif'
        | '"Inter", sans-serif'
        | '"Poppins", sans-serif'
        | '"Raleway", sans-serif'
      )
    | null;
  /**
   * Por defecto: gris claro.
   */
  subtitleColor?: string | null;
  /**
   * Por defecto usa la misma tipografía que el hero MicroVisuals (Instrument Serif + Barlow).
   */
  subtitleFontFamily?:
    | (
        | 'default'
        | '"Instrument Serif", serif'
        | 'Arial, sans-serif'
        | '"Times New Roman", serif'
        | 'Georgia, serif'
        | 'Verdana, sans-serif'
        | 'Helvetica, Arial, sans-serif'
        | '"Courier New", monospace'
        | '"Roboto", sans-serif'
        | '"Open Sans", sans-serif'
        | '"Lato", sans-serif'
        | '"Montserrat", sans-serif'
        | '"Playfair Display", serif'
        | '"Inter", sans-serif'
        | '"Poppins", sans-serif'
        | '"Raleway", sans-serif'
      )
    | null;
  /**
   * Por defecto: blanco.
   */
  cardBackgroundColor?: string | null;
  /**
   * Por defecto: transparente.
   */
  cardBorderColor?: string | null;
  /**
   * Por defecto: negro.
   */
  questionColor?: string | null;
  /**
   * Por defecto usa la misma tipografía que el hero MicroVisuals (Instrument Serif + Barlow).
   */
  questionFontFamily?:
    | (
        | 'default'
        | '"Instrument Serif", serif'
        | 'Arial, sans-serif'
        | '"Times New Roman", serif'
        | 'Georgia, serif'
        | 'Verdana, sans-serif'
        | 'Helvetica, Arial, sans-serif'
        | '"Courier New", monospace'
        | '"Roboto", sans-serif'
        | '"Open Sans", sans-serif'
        | '"Lato", sans-serif'
        | '"Montserrat", sans-serif'
        | '"Playfair Display", serif'
        | '"Inter", sans-serif'
        | '"Poppins", sans-serif'
        | '"Raleway", sans-serif'
      )
    | null;
  /**
   * Por defecto: gris oscuro.
   */
  answerColor?: string | null;
  /**
   * Por defecto usa la misma tipografía que el hero MicroVisuals (Instrument Serif + Barlow).
   */
  answerFontFamily?:
    | (
        | 'default'
        | '"Instrument Serif", serif'
        | 'Arial, sans-serif'
        | '"Times New Roman", serif'
        | 'Georgia, serif'
        | 'Verdana, sans-serif'
        | 'Helvetica, Arial, sans-serif'
        | '"Courier New", monospace'
        | '"Roboto", sans-serif'
        | '"Open Sans", sans-serif'
        | '"Lato", sans-serif'
        | '"Montserrat", sans-serif'
        | '"Playfair Display", serif'
        | '"Inter", sans-serif'
        | '"Poppins", sans-serif'
        | '"Raleway", sans-serif'
      )
    | null;
  /**
   * Por defecto: verde oscuro.
   */
  iconBackgroundColor?: string | null;
  /**
   * Por defecto: blanco.
   */
  iconColor?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'faqs';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reservations".
 */
export interface Reservation {
  id: number;
  product: number | Product;
  status: 'pending' | 'contacted' | 'ready' | 'collected' | 'cancelled';
  fullName: string;
  mobile: string;
  email: string;
  message?: string | null;
  hp_field?: string | null;
  submittedFromIP?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: number;
  /**
   * You will need to rebuild the website when changing this field.
   */
  from: string;
  to?: {
    type?: ('reference' | 'custom') | null;
    reference?:
      | ({
          relationTo: 'pages';
          value: number | Page;
        } | null)
      | ({
          relationTo: 'posts';
          value: number | Post;
        } | null);
    url?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions".
 */
export interface FormSubmission {
  id: number;
  form: number | Form;
  submissionData?:
    | {
        field: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This is a collection of automatically created search results. These results are used by the global site search and will be updated automatically as documents in the CMS are created or updated.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search".
 */
export interface Search {
  id: number;
  title?: string | null;
  priority?: number | null;
  doc: {
    relationTo: 'posts';
    value: number | Post;
  };
  slug?: string | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
  };
  categories?:
    | {
        relationTo?: string | null;
        categoryID?: string | null;
        title?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'schedulePublish';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'schedulePublish') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'reservations';
        value: number | Reservation;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'redirects';
        value: number | Redirect;
      } | null)
    | ({
        relationTo: 'forms';
        value: number | Form;
      } | null)
    | ({
        relationTo: 'form-submissions';
        value: number | FormSubmission;
      } | null)
    | ({
        relationTo: 'search';
        value: number | Search;
      } | null)
    | ({
        relationTo: 'payload-folders';
        value: number | FolderInterface;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  hero?:
    | T
    | {
        type?: T;
        richText?: T;
        links?:
          | T
          | {
              link?:
                | T
                | {
                    type?: T;
                    newTab?: T;
                    reference?: T;
                    url?: T;
                    label?: T;
                    appearance?: T;
                  };
              id?: T;
            };
        media?: T;
        microVisuals?:
          | T
          | {
              title?: T;
              videoUrl?: T;
              backgroundVideo?: T;
              navItems?:
                | T
                | {
                    link?:
                      | T
                      | {
                          type?: T;
                          newTab?: T;
                          reference?: T;
                          url?: T;
                          label?: T;
                        };
                    id?: T;
                  };
              leftCaption?: T;
              rightCaption?: T;
              signIn?:
                | T
                | {
                    type?: T;
                    newTab?: T;
                    reference?: T;
                    url?: T;
                    label?: T;
                  };
              tryItFree?:
                | T
                | {
                    type?: T;
                    newTab?: T;
                    reference?: T;
                    url?: T;
                    label?: T;
                  };
              primaryCta?:
                | T
                | {
                    type?: T;
                    newTab?: T;
                    reference?: T;
                    url?: T;
                    label?: T;
                  };
              secondaryCta?:
                | T
                | {
                    type?: T;
                    newTab?: T;
                    reference?: T;
                    url?: T;
                    label?: T;
                  };
              showSecondaryIcon?: T;
            };
        heroSoria?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              subtitle?: T;
              buttons?:
                | T
                | {
                    link?:
                      | T
                      | {
                          type?: T;
                          newTab?: T;
                          reference?: T;
                          url?: T;
                          label?: T;
                        };
                    appearance?: T;
                    fontFamily?: T;
                    backgroundColor?: T;
                    textColor?: T;
                    id?: T;
                  };
              gallery?:
                | T
                | {
                    image?: T;
                    rotation?: T;
                    alt?: T;
                    id?: T;
                  };
              titleColor?: T;
              titleFontFamily?: T;
              subtitleColor?: T;
              subtitleFontFamily?: T;
              eyebrowColor?: T;
              eyebrowFontFamily?: T;
              backgroundColor?: T;
            };
      };
  layout?:
    | T
    | {
        cta?: T | CallToActionBlockSelect<T>;
        content?: T | ContentBlockSelect<T>;
        mediaBlock?: T | MediaBlockSelect<T>;
        archive?: T | ArchiveBlockSelect<T>;
        formBlock?: T | FormBlockSelect<T>;
        productsBlock?: T | ProductsBlockSelect<T>;
        layoutSoria?: T | LayoutSoriaBlockSelect<T>;
        layoutSoria2?: T | LayoutSoria2BlockSelect<T>;
        locationBlock?: T | LocationBlockSelect<T>;
        serviciosSoria?: T | ServiciosSoriaBlockSelect<T>;
        faqs?: T | FAQsBlockSelect<T>;
      };
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  publishedAt?: T;
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionBlock_select".
 */
export interface CallToActionBlockSelect<T extends boolean = true> {
  background?:
    | T
    | {
        type?: T;
        image?: T;
        videoURL?: T;
        solidColor?: T;
        gradientFrom?: T;
        gradientTo?: T;
        overlayOpacity?: T;
      };
  buttonsPosition?: T;
  richText?: T;
  links?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              appearance?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock_select".
 */
export interface ContentBlockSelect<T extends boolean = true> {
  columns?:
    | T
    | {
        size?: T;
        richText?: T;
        enableLink?: T;
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              appearance?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock_select".
 */
export interface MediaBlockSelect<T extends boolean = true> {
  media?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ArchiveBlock_select".
 */
export interface ArchiveBlockSelect<T extends boolean = true> {
  introContent?: T;
  populateBy?: T;
  relationTo?: T;
  categories?: T;
  limit?: T;
  selectedDocs?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormBlock_select".
 */
export interface FormBlockSelect<T extends boolean = true> {
  form?: T;
  enableIntro?: T;
  introContent?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ProductsBlock_select".
 */
export interface ProductsBlockSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  populateBy?: T;
  limit?: T;
  selectedProducts?: T;
  carousel?: T;
  backgroundColor?: T;
  textColor?: T;
  titleFontFamily?: T;
  descriptionFontFamily?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LayoutSoriaBlock_select".
 */
export interface LayoutSoriaBlockSelect<T extends boolean = true> {
  anchorId?: T;
  richText?: T;
  image?:
    | T
    | {
        useMedia?: T;
        mediaImage?: T;
        useViewportSize?: T;
        mediaWidthVw?: T;
        mediaHeightVh?: T;
        mediaWidthVwMobile?: T;
        mediaHeightVhMobile?: T;
        src?: T;
        alt?: T;
      };
  subHeadings?:
    | T
    | {
        icon?:
          | T
          | {
              useMedia?: T;
              mediaImage?: T;
              iconSVG?: T;
              alt?: T;
            };
        content?: T;
        id?: T;
      };
  buttons?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
        appearance?: T;
        size?: T;
        iconSVG?: T;
        id?: T;
      };
  invertLayout?: T;
  backgroundColor?: T;
  applyCustomWidth?: T;
  customWidthPercent?: T;
  customWidthPercentMobile?: T;
  textColor?: T;
  boldTextColor?: T;
  buttonBackgroundColor?: T;
  buttonTextColor?: T;
  fontFamily?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LayoutSoria2Block_select".
 */
export interface LayoutSoria2BlockSelect<T extends boolean = true> {
  anchorId?: T;
  heading?: T;
  description?: T;
  stats?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  image?: T;
  imageAlt?: T;
  imagePosition?: T;
  backgroundColor?: T;
  headingColor?: T;
  descriptionColor?: T;
  statCardBackground?: T;
  statNumberColor?: T;
  statLabelColor?: T;
  cornerRadius?: T;
  fontFamily?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LocationBlock_select".
 */
export interface LocationBlockSelect<T extends boolean = true> {
  businessName?: T;
  description?: T;
  address?:
    | T
    | {
        streetAddress?: T;
        postalCode?: T;
        addressLocality?: T;
        addressRegion?: T;
        addressCountry?: T;
      };
  phone?: T;
  email?: T;
  embedUrl?: T;
  geo?:
    | T
    | {
        latitude?: T;
        longitude?: T;
      };
  openingHours?:
    | T
    | {
        daysOfWeek?: T;
        opens?: T;
        closes?: T;
        closed?: T;
        id?: T;
      };
  priceRange?: T;
  backgroundColor?: T;
  textColor?: T;
  headingFontFamily?: T;
  bodyFontFamily?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ServiciosSoriaBlock_select".
 */
export interface ServiciosSoriaBlockSelect<T extends boolean = true> {
  anchorId?: T;
  eyebrow?: T;
  title?: T;
  subtitle?: T;
  services?:
    | T
    | {
        image?: T;
        label?: T;
        description?: T;
        cta?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
        id?: T;
      };
  autoplay?: T;
  autoplayMs?: T;
  backgroundColor?: T;
  titleColor?: T;
  titleFontFamily?: T;
  subtitleColor?: T;
  subtitleFontFamily?: T;
  cardTextColor?: T;
  cardFontFamily?: T;
  ctaBackgroundColor?: T;
  ctaTextColor?: T;
  ctaFontFamily?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FAQsBlock_select".
 */
export interface FAQsBlockSelect<T extends boolean = true> {
  anchorId?: T;
  title?: T;
  subtitle?: T;
  items?:
    | T
    | {
        question?: T;
        answer?: T;
        defaultOpen?: T;
        id?: T;
      };
  allowMultipleOpen?: T;
  backgroundColor?: T;
  maxWidth?: T;
  titleColor?: T;
  titleFontFamily?: T;
  subtitleColor?: T;
  subtitleFontFamily?: T;
  cardBackgroundColor?: T;
  cardBorderColor?: T;
  questionColor?: T;
  questionFontFamily?: T;
  answerColor?: T;
  answerFontFamily?: T;
  iconBackgroundColor?: T;
  iconColor?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  heroImage?: T;
  content?: T;
  relatedPosts?: T;
  categories?: T;
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  publishedAt?: T;
  authors?: T;
  populatedAuthors?:
    | T
    | {
        id?: T;
        name?: T;
      };
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  folder?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        square?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        small?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        medium?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        large?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        xlarge?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  generateSlug?: T;
  slug?: T;
  parent?: T;
  breadcrumbs?:
    | T
    | {
        doc?: T;
        url?: T;
        label?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  title?: T;
  sku?: T;
  price?: T;
  availability?: T;
  shortDescription?: T;
  description?: T;
  images?: T;
  allowReservation?: T;
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reservations_select".
 */
export interface ReservationsSelect<T extends boolean = true> {
  product?: T;
  status?: T;
  fullName?: T;
  mobile?: T;
  email?: T;
  message?: T;
  hp_field?: T;
  submittedFromIP?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  from?: T;
  to?:
    | T
    | {
        type?: T;
        reference?: T;
        url?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms_select".
 */
export interface FormsSelect<T extends boolean = true> {
  title?: T;
  fields?:
    | T
    | {
        checkbox?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              defaultValue?: T;
              id?: T;
              blockName?: T;
            };
        country?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        email?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        message?:
          | T
          | {
              message?: T;
              id?: T;
              blockName?: T;
            };
        number?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        select?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              placeholder?: T;
              options?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              required?: T;
              id?: T;
              blockName?: T;
            };
        state?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        text?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        textarea?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
      };
  submitButtonLabel?: T;
  confirmationType?: T;
  confirmationMessage?: T;
  redirect?:
    | T
    | {
        url?: T;
      };
  emails?:
    | T
    | {
        emailTo?: T;
        cc?: T;
        bcc?: T;
        replyTo?: T;
        emailFrom?: T;
        subject?: T;
        message?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions_select".
 */
export interface FormSubmissionsSelect<T extends boolean = true> {
  form?: T;
  submissionData?:
    | T
    | {
        field?: T;
        value?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search_select".
 */
export interface SearchSelect<T extends boolean = true> {
  title?: T;
  priority?: T;
  doc?: T;
  slug?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  categories?:
    | T
    | {
        relationTo?: T;
        categoryID?: T;
        title?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-folders_select".
 */
export interface PayloadFoldersSelect<T extends boolean = true> {
  name?: T;
  folder?: T;
  documentsAndFolders?: T;
  folderType?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  /**
   * Elige qué navbar quieres usar en la web. Al cambiar de tipo, los campos específicos se mostrarán u ocultarán automáticamente.
   */
  type: 'default' | 'navbarSoria';
  navItems?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null);
          url?: string | null;
          label: string;
        };
        id?: string | null;
      }[]
    | null;
  /**
   * Variante del header con logotipo + barra lateral de menús. En escritorio se muestran los items en línea; en móvil se abre un panel lateral.
   */
  navbarSoria?: {
    /**
     * Imagen del logotipo (preferiblemente SVG o PNG con fondo transparente).
     */
    logo?: (number | null) | Media;
    /**
     * Se muestra junto al logotipo o como reemplazo si no hay imagen. Ej.: "Casa Soria".
     */
    logoText?: string | null;
    /**
     * Lista de enlaces que se muestran en la barra (horizontal en escritorio y dentro del panel lateral en móvil).
     */
    sidebarItems?:
      | {
          link: {
            type?: ('reference' | 'custom') | null;
            newTab?: boolean | null;
            reference?:
              | ({
                  relationTo: 'pages';
                  value: number | Page;
                } | null)
              | ({
                  relationTo: 'posts';
                  value: number | Post;
                } | null);
            url?: string | null;
            label: string;
          };
          id?: string | null;
        }[]
      | null;
    /**
     * Botón destacado al final del menú (por ejemplo, "Reservar"). Déjalo vacío si no quieres mostrarlo.
     */
    cta: {
      link: {
        type?: ('reference' | 'custom') | null;
        newTab?: boolean | null;
        reference?:
          | ({
              relationTo: 'pages';
              value: number | Page;
            } | null)
          | ({
              relationTo: 'posts';
              value: number | Post;
            } | null);
        url?: string | null;
        label: string;
      };
    };
    /**
     * Opcional. Cualquier color CSS (#hex, rgb, oklch…).
     */
    backgroundColor?: string | null;
    textColor?: string | null;
    /**
     * Si lo activas, el navbar queda siempre fijo arriba. Si lo dejas desactivado, el navbar se oculta al hacer scroll hacia abajo y vuelve a bajar al hacer scroll hacia arriba.
     */
    sticky?: boolean | null;
    /**
     * Si lo activas, el menú lateral se abre siempre con el botón hamburguesa (también en pantallas grandes).
     */
    showHamburgerOnDesktop?: boolean | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  navItems?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null);
          url?: string | null;
          label: string;
        };
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  type?: T;
  navItems?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
        id?: T;
      };
  navbarSoria?:
    | T
    | {
        logo?: T;
        logoText?: T;
        sidebarItems?:
          | T
          | {
              link?:
                | T
                | {
                    type?: T;
                    newTab?: T;
                    reference?: T;
                    url?: T;
                    label?: T;
                  };
              id?: T;
            };
        cta?:
          | T
          | {
              link?:
                | T
                | {
                    type?: T;
                    newTab?: T;
                    reference?: T;
                    url?: T;
                    label?: T;
                  };
            };
        backgroundColor?: T;
        textColor?: T;
        sticky?: T;
        showHamburgerOnDesktop?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  navItems?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null;
    locale?: string | null;
    doc?:
      | ({
          relationTo: 'pages';
          value: number | Page;
        } | null)
      | ({
          relationTo: 'posts';
          value: number | Post;
        } | null);
    global?: string | null;
    user?: (number | null) | User;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BannerBlock".
 */
export interface BannerBlock {
  style: 'info' | 'warning' | 'error' | 'success';
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'banner';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CodeBlock".
 */
export interface CodeBlock {
  language?: ('typescript' | 'javascript' | 'css') | null;
  code: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'code';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}